### ISSUE TITLE
开始运行后一直白屏

### ISSUE THREAD

**Issue by iQNRen** [kevinwu06/FighterDuck#1]
ui_gameEngine.h没发全吧

**Comment by iQNRen** [comment]
ui_gameEngine.h没发全吧

**Comment by kmeykranz** [comment]
不好意思，之前上传的有点问题😣，我修改了下，现在可以了

**Comment by iQNRen** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
